### ISSUE TITLE
Monitor updates to required packages with requires.io

### ISSUE THREAD

**Issue by ameistad** [Djenesis/contributr#40]
I suggest using requires.io to monitor updates to packages in requirements/*.

**Comment by coolharsh55** [comment]
Good idea? I see no harm in signing up for this. However, it mentions that _Github Organisations_ require a **business plan**.

> Update: only for **private** organisations. Djenesis can sign up for free since it has a public repo.

**Comment by ameistad** [comment]
I would think it only requires a free plan as long as it's a private repository. But I'm not 100% sure.

**Comment by coolharsh55** [comment]
Check Djenesis status at https://requires.io/github/Djenesis/contributr/requirements/?branch=master
