### ISSUE TITLE
test coverage is low

### ISSUE THREAD

**Issue by SanketDG** [Djenesis/contributr#50]
Currently, [coverage](https://coveralls.io/github/Djenesis/contributr?branch=master#) is pretty low. We need to decide on ignoring files correctly in `.coveragerc` that cannot be tested, and also add more tests.

**Comment by tobias47n9e** [comment]
I think this has to be related to Coveralls not finding our files correctly. It runs the tests, but on the website none of the files can be viewed. When I click on the files it says "source not available".
