### ISSUE TITLE
Database settings

### ISSUE THREAD

**Issue by ameistad** [Djenesis/contributr#53]
I suggest we move the database settings in base.py to local.py. We already have settings for Heroku in production.py and there is no need to import local database settings in production. 

I also suggest we read database settings in local from environment variables. 
If you want to use PostgreSQL you can set the the variable with 

```
export DATABASE_URL=postgres://username:password@127.0.0.1:5432/contributr
# or just
export DATABASE_URL=postgres:///contributr
# for windows
export DATABASE_URL=postgres://localhost/contributr
# sqlite3 example
export DATABASE_URL=sqlite:///db.sqlite3
```

**Comment by SanketDG** [comment]
@ameistad Do we really need to load the database settings from a environment variable. Using sqlite3 locally and postgres in production is sufficient and just works.

**Comment by ameistad** [comment]
Yeah, doesn't  matter much, only matters if somebody uses a password on the local database. But let's keep it as is for simplicity.
